apiVersion: v1
kind: Service
metadata:
  name: spire-server
  namespace: spire
spec:
  type: NodePort
  ports:
    - name: grpc
      nodePort: 30000
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: spire-server
